name: health_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  talker_flutter: ^4.2.0
  flutter_secure_storage: ^4.2.1
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dio: ^5.4.3+1
  get_it: ^7.7.0
  talker_dio_logger: ^4.1.5
  talker_bloc_logger: ^4.2.0
  cupertino_icons: ^1.0.2
  uuid: ^4.4.0
  dart_jsonwebtoken: ^2.14.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
